name: Deploy Automático no Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Fazer Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: tcp://0.tcp.sa.ngrok.io:15014  
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/site-devops
          git pull origin main
          sudo systemctl reload nginx
        port: 22
        debug: true
